/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  Home: [
    'Home',
    { type: 'autogenerated', dirName: 'Home' }
  ],

  其它: [
    { type: 'autogenerated', dirName: 'Other' }
  ],


  计算机: [
    { type: 'autogenerated', dirName: 'Computer' }
  ],


  数学: [
    { type: 'autogenerated', dirName: 'Math' }
  ],


  MC: [
    { type: 'autogenerated', dirName: 'MC' }
  ],

  IL: [
    { type: 'autogenerated', dirName: 'IL' }
  ],

  Life: [
    { type: 'autogenerated', dirName: 'Life' }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
